### ISSUE TITLE
minor wording suggestion in breakfast menu

### ISSUE THREAD

**Issue by jbrucker** [ISP19/kucafe2#4]
Breakfast menu looks good.  2 wording suggestions.

"Actual sandwich" change "Actual" to "Regular" or "Premium"
(to differentiate from "Economy sandwich").

"Fried Eggs with rice"   capitalize "R" in "rice", for consistency.

**Comment by patdpat** [comment]
Acknowledged and fixed the breakfast menu.
Thanks :D 👍
